apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-app
  namespace: app
  labels:
    app: tcc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcc-app
  template:
    metadata:
      labels:
        app: tcc-app
    spec:
      containers:
        - name: tcc-app
          image: ghcr.io/cristopherpds/tcc-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PROJECT_ID

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20