apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-ossn-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcc-ossn-app
  template:
    metadata:
      labels:
        app: tcc-ossn-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: tcc-ossn-app
        image: ghcr.io/cristopherpds/tcc-ossn-app:v0.5.2
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: tcc-ossn-config
                key: DB_HOST
          - name: OSSN_DATA
            valueFrom:
              configMapKeyRef:
                name: tcc-ossn-config
                key: OSSN_DATA
          - name: WEBSITE_NAME
            valueFrom:
              configMapKeyRef:
                name: tcc-ossn-config
                key: WEBSITE_NAME
          - name: SITE_OWNER_EMAIL
            valueFrom:
              configMapKeyRef:
                name: tcc-ossn-config
                key: SITE_OWNER_EMAIL
          - name: NOTIFICATION_EMAIL
            valueFrom:
              configMapKeyRef:
                name: tcc-ossn-config
                key: NOTIFICATION_EMAIL
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: tcc-ossn-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tcc-ossn-secret
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: tcc-ossn-secret
                key: MYSQL_DATABASE
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tcc-ossn-secret
                key: MYSQL_ROOT_PASSWORD