apiVersion: v1
kind: Secret
metadata:
  name: tcc-ossn-secret
  namespace: app
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"name":"tcc-ossn-secret","namespace":"app"},"type":"Opaque","stringData":{"MYSQL_USER":"{{ MYSQL_USER }}","MYSQL_PASSWORD":"{{ MYSQL_PASSWORD }}","MYSQL_DATABASE":"{{ MYSQL_DATABASE }}","MYSQL_ROOT_PASSWORD":"{{ MYSQL_ROOT_PASSWORD }}"}}
type: Opaque
stringData:
  MYSQL_USER: "{{ MYSQL_USER }}"
  MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
  MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
  MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"