apiVersion: v1
kind: ConfigMap
metadata:
  name: tcc-ossn-config
  namespace: app
data:
  OSSN_DATA: "/var/www/ossn_data"
  WEBSITE_NAME: "TCC POC GITOPS"
  SITE_OWNER_EMAIL: "TCC Social Network"
  NOTIFICATION_EMAIL: "noreply@tcc.local"
  DB_HOST: "mysql"