apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tcc-app
  namespace: argocd
spec:
  project: app-project

  source:
    repoURL: https://github.com/cristopherpds/tcc-ops.git
    targetRevision: deploy/app
    path: k8s
  
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true