apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tcc-ops-project
  namespace: argocd
spec:
  description: "Proyecto para la app TCC-OSSN"
  sourceRepos:
    - https://github.com/cristopherpds/tcc-ops.git
  destinations:
    - namespace: app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'